import React, {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";
import * as SecureStore from "expo-secure-store";

export type AppLanguage = "en" | "ar";

type LanguageContextType = {
  language: AppLanguage;
  isRTL: boolean;
  isLoading: boolean;
  setLanguage: (next: AppLanguage) => Promise<void>;
  t: (key: string) => string;
};

const STORAGE_KEY = "app_language";

const en: Record<string, string> = {
  "tabs.home": "Home",
  "tabs.settings": "Settings",
  "common.cancel": "Cancel",

  "settings.title": "Settings",
  "settings.subtitle": "Customize your movement through the city.",
  "settings.userFallback": "User",
  "settings.section.transportation": "Transportation",
  "settings.hint.title": "What you can do here",
  "settings.hint.message": "Open Routes or History from this screen. Preferences are available in Home.",
  "settings.routes.title": "Routes Map",
  "settings.routes.subtitle": "View and toggle active bus lines",
  "settings.preferences.title": "Preferences",
  "settings.preferences.subtitle": "Customize routing factors",
  "settings.history.title": "Travel History",
  "settings.history.subtitle": "See and manage your saved route history",
  "settings.language.title": "Language",
  "settings.language.subtitle": "Choose app language",
  "settings.signout": "Sign Out",

  "language.english": "English",
  "language.arabic": "Arabic",

  "preferences.title": "Preferences",
  "preferences.heroLabel": "Customization",
  "preferences.heroTitle": "Routing Preferences",
  "preferences.heroSubtitle":
    "Adjust and save weights/options used by routing.",
  "preferences.loading": "Loading saved values...",
  "preferences.speed": "Speed",
  "preferences.crowding": "Avoid Crowds",
  "preferences.price": "Price Sensitivity",
  "preferences.transfer": "Fewer Transfers",
  "preferences.walking": "Walking",
  "preferences.options.section": "Routing Options",
  "preferences.options.maxWalkingDistance": "Max Walking Distance (m)",
  "preferences.options.maxTotalWalkingDistance":
    "Max Total Walking Distance (m)",
  "preferences.options.maxWalkingNeighbors": "Max Walking Neighbors",
  "preferences.options.maxBusTransfers": "Max Bus Transfers",
  "preferences.options.walkingSpeed": "Walking Speed (m/s)",
  "preferences.hint.min50": "min 50",
  "preferences.hint.rangeWalkTotal": "range 0 .. 10000",
  "preferences.hint.rangeNeighbors": "range 1 .. 100",
  "preferences.hint.rangeTransfers": "range 0 .. 10",
  "preferences.hint.rangeSpeed": "range 0.4 .. 3.5",
  "preferences.save": "Save Preferences",
  "preferences.saveError": "Could not save preferences.",

  "history.title": "Travel History",
  "history.subtitle": "User #{id} - last {limit} trips",
  "history.refresh": "Refresh",
  "history.loading": "Loading history...",
  "history.loadError":
    "Could not load travel history. Pull to retry or tap refresh.",
  "history.empty": "No history entries yet.",
  "history.delete": "Delete",
  "history.deleteTitle": "Delete Entry",
  "history.deleteBody":
    "Are you sure you want to remove this travel history item?",
  "history.deleteSuccess": "History entry deleted.",
  "history.deleteError": "Could not delete history entry.",
  "history.unknownOrigin": "Unknown origin",
  "history.unknownDest": "Unknown destination",
  "history.unknownTime": "Unknown time",
  "history.metric.transfers": "Transfers",
  "history.metric.distance": "Distance",
  "history.metric.duration": "Duration",
  "history.metric.routes": "Routes",
  "history.useAgain": "Use again",
  "history.completedTrip": "Completed trip",
  "history.cachedRouteLoaded": "Saved route loaded",

  "planner.title": "Route Planner",
  "planner.pref.loading": "Loading saved preferences...",
  "planner.pref.saved": "Using saved preferences",
  "planner.pref.defaults": "Using server defaults",
  "planner.start": "Start",
  "planner.destination": "Destination",
  "planner.tapStart": "Tap Map: Set Start",
  "planner.tapDestination": "Tap Map: Set Destination",
  "planner.locked": "Route is locked. Press Clear to choose a new destination.",
  "planner.request": "Request Route",
  "planner.clear": "Clear",
  "planner.actions": "Route actions",
  "planner.preferences": "Preferences",
  "planner.filter.balanced": "Best",
  "planner.filter.fastest": "Fastest",
  "planner.filter.fewestTransfers": "Few transfers",
  "planner.filter.lessWalking": "Less walking",
  "planner.filter.cheapest": "Cheapest",
  "planner.filter.lessCrowded": "Less crowded",
  "planner.textPlaceholder":
    "Try: from Bab Touma to Hamra / من باب توما إلى الحمراء",
  "planner.useText": "Use Text",
  "planner.nlp.title": "Describe your trip",
  "planner.nlp.needOrigin": "Where are you starting from?",
  "planner.nlp.needDestination": "Where do you want to go?",
  "planner.nlp.needClarification": "Which place did you mean?",

  "prefModal.title": "Route preferences",
  "prefModal.subtitle": "These change how routes are searched",
  "prefModal.loading": "Loading preferences...",
  "prefModal.walkingTolerance": "How much walking is okay?",
  "prefModal.walkingDescription": "Sets the longest walk to stops and total walking in a route.",
  "prefModal.walking.low": "Short walks",
  "prefModal.walking.medium": "Normal walks",
  "prefModal.walking.high": "Longer walks",
  "prefModal.transferLimit": "How many bus changes?",
  "prefModal.transferDescription": "Limits how many times the route may switch buses.",
  "prefModal.transfer.none": "Direct only",
  "prefModal.transfer.one": "1 change",
  "prefModal.transfer.two": "2 changes",
  "prefModal.transfer.flexible": "More options",
  "prefModal.walkingPace": "Your walking speed",
  "prefModal.paceDescription": "Used to estimate walking time.",
  "prefModal.pace.slow": "Relaxed",
  "prefModal.pace.normal": "Average",
  "prefModal.pace.fast": "Fast walker",
  "prefModal.searchBreadth": "How many route options?",
  "prefModal.breadthDescription": "Wider search can find better routes, but may take longer.",
  "prefModal.breadth.compact": "Faster search",
  "prefModal.breadth.balanced": "Balanced",
  "prefModal.breadth.wide": "More options",
  "prefModal.cancel": "Cancel",
  "prefModal.save": "Save",

  "search.placeholder": "Search place on map",
  "map.startFallback": "Your location",
  "map.destinationFallback": "Choose destination",
  "map.destinationPin": "Destination",
  "map.pinnedStart": "Pinned start",
  "map.pinnedDestination": "Pinned destination",
  "map.mapPoint": "Selected on map",

  "route.eta": "ETA",
  "route.min": "min",
  "route.transfer": "transfer",
  "route.transfers": "Transfers",
  "route.walk": "Walk",
  "route.share.action": "Share",
  "route.share.title": "Shared Route",
  "route.share.start": "Start",
  "route.share.destination": "Destination",
  "route.share.googleMapsLabel": "Open in Google Maps",
  "route.share.appLinkLabel": "Open in JR app",
  "route.share.universalLinkLabel": "Open route link",
  "route.share.failedTitle": "Share failed",
  "route.share.failedBody": "Could not share this route right now.",
  "route.trip.ready": "Ready to go",
  "route.trip.inProgress": "Route in progress",
  "route.trip.startHint": "Start when you actually take this route.",
  "route.trip.finishHint": "Finish when you arrive to save this route.",
  "route.trip.start": "Start",
  "route.trip.finish": "Finish",
  "route.trip.saving": "Saving",
  "route.trip.started": "Route started",
  "route.trip.saved": "Route saved",
  "route.trip.saveFailedTitle": "Could not save trip",
  "route.trip.saveFailed": "Could not save this trip right now.",
  "routePoint": "Route point",

  "steps.walk": "Walk",
  "steps.takeBus": "Take Bus",
  "steps.routeFallback": "Route",
  "steps.via": "via",

  "feedback.title": "Route Feedback",
  "feedback.hide": "Hide",
  "feedback.give": "Give Feedback",
  "feedback.route": "Route",
  "feedback.summary": "Route Feedback Summary (30 days)",
  "feedback.loadingSummary": "Loading summary...",
  "feedback.reports": "Reports",
  "feedback.avgPrice": "Avg Price",
  "feedback.avgCrowding": "Avg Crowding",
  "feedback.avgSpeed": "Avg Speed",
  "feedback.avgSlowness": "Avg Slowness",
  "feedback.crowdingTendency": "Crowding Tendency",
  "feedback.speedSuggestion": "Speed Suggestion",
  "feedback.lastReport": "Last Report",
  "feedback.noSummary": "No summary available yet.",
  "feedback.reportedPrice": "Reported Price",
  "feedback.crowdingLevel": "Crowding Level",
  "feedback.speedLevel": "Speed Level",
  "feedback.slownessLevel": "Slowness Level",
  "feedback.comment": "Comment (Optional)",
  "feedback.commentPlaceholder": "Share your experience",
  "feedback.skip": "Skip",
  "feedback.submit": "Submit Feedback",
  "feedback.thanks": "Thanks",
  "feedback.submitted": "Feedback submitted successfully.",
  "feedback.missingRouteTitle": "Missing route",
  "feedback.missingRouteBody": "Select a bus route to submit feedback.",
  "feedback.invalidPriceTitle": "Invalid price",
  "feedback.invalidPriceBody": "Reported price must be 0 or greater.",

  "home.error.missingPointsTitle": "Missing points",
  "home.error.missingPointsBody":
    "Current location and destination are required.",
  "home.error.routeFailedTitle": "Route request failed",
  "home.error.searchNoPlaceTitle": "No place found",
  "home.error.searchNoPlaceBody": "Try a more specific place name.",
  "home.error.searchFailedTitle": "Search failed",
  "home.error.searchFailedBody": "Could not search places right now.",
  "home.error.locationPermission": "Location permission not granted.",
  "home.filterUpdateFailedTitle": "Filter update failed",
  "home.chooseDestinationFirstTitle": "Choose destination first",
  "home.chooseDestinationFirstBody": "Pick a destination on the map or search before selecting your start location.",
  "home.crosshair.title": "Choose start location",
  "home.crosshair.subtitle": "Pan and zoom map under pin",
  "home.crosshair.set": "Set",
  "home.crosshair.setStart": "Set start",
  "home.crosshair.setDestination": "Set destination",
  "home.origin.header": "Choose start point",
  "home.origin.subtitle": "Search, use the map, or choose a saved place.",
  "home.origin.searchPlaceholder": "Search start point",
  "home.origin.chooseFromMap": "Choose from Map",
  "home.origin.useCurrent": "Use Current Location",
  "home.origin.favorites": "Favorites",
  "home.origin.saveCurrentFavorite": "Save current location as a favorite",
  "home.destination.header": "Choose destination",
  "home.destination.subtitle": "Search, use the map, or choose a saved place.",
  "home.destination.searchPlaceholder": "Search destination",
  "home.destination.useCurrent": "Use Current Location",
  "home.confirm.clearTitle": "Clear route?",
  "home.confirm.clearBody": "This removes the current points and route from the map.",
  "home.confirm.swapTitle": "Swap start and destination?",
  "home.confirm.swapBody": "The current start point will become the destination.",
  "home.confirm.swapAction": "Swap",
  "home.routeFound": "{count} route found",
  "home.startHereTitle": "Start here",
  "home.startHereBody": "Pick a destination, choose a start point, then request a route.",
  "home.results.publicTransport": "Public transport",
  "home.results.tapToExpand": "Tap a route to expand it",
  "home.results.routeDetails": "Route details",
  "home.results.live": "Live route",
  "home.results.liveFallback": "Live fallback route",
};

const ar: Record<string, string> = {
  "tabs.home": "الرئيسية",
  "tabs.settings": "الإعدادات",
  "common.cancel": "إلغاء",
  "home.crosshair.setStart": "تحديد البداية",
  "home.crosshair.setDestination": "تحديد الوجهة",
  "home.origin.subtitle": "ابحث أو استخدم الخريطة أو اختر مكانا محفوظا.",
  "home.origin.searchPlaceholder": "ابحث عن البداية",
  "home.destination.header": "اختر الوجهة",
  "home.destination.subtitle": "ابحث أو استخدم الخريطة أو اختر مكانا محفوظا.",
  "home.destination.searchPlaceholder": "ابحث عن الوجهة",
  "home.destination.useCurrent": "استخدم موقعي الحالي",
  "home.confirm.clearTitle": "مسح المسار؟",
  "home.confirm.clearBody": "سيتم حذف النقاط والمسار الحالي من الخريطة.",
  "home.confirm.swapTitle": "تبديل البداية والوجهة؟",
  "home.confirm.swapBody": "ستصبح نقطة البداية الحالية هي الوجهة.",
  "home.confirm.swapAction": "تبديل",
  "home.routeFound": "تم العثور على {count} مسار",

  "settings.title": "الإعدادات",
  "settings.subtitle": "خصص تنقلك داخل المدينة.",
  "settings.userFallback": "مستخدم",
  "settings.section.transportation": "النقل",
  "settings.hint.title": "ما الذي يمكنك فعله هنا",
  "settings.hint.message": "يمكنك فتح الخطوط أو السجل من هذه الشاشة. التفضيلات متاحة في الشاشة الرئيسية.",
  "settings.routes.title": "خريطة الخطوط",
  "settings.routes.subtitle": "عرض وتبديل خطوط الباص",
  "settings.preferences.title": "التفضيلات",
  "settings.preferences.subtitle": "تخصيص عوامل التوجيه",
  "settings.history.title": "سجل الرحلات",
  "settings.history.subtitle": "عرض وإدارة سجل الرحلات",
  "settings.language.title": "اللغة",
  "settings.language.subtitle": "اختر لغة التطبيق",
  "settings.signout": "تسجيل الخروج",

  "language.english": "الإنجليزية",
  "language.arabic": "العربية",

  "preferences.title": "التفضيلات",
  "preferences.heroLabel": "تخصيص",
  "preferences.heroTitle": "تفضيلات التوجيه",
  "preferences.heroSubtitle":
    "عدّل واحفظ الأوزان والخيارات المستخدمة في التوجيه.",
  "preferences.loading": "جاري تحميل القيم المحفوظة...",
  "preferences.speed": "السرعة",
  "preferences.crowding": "تجنب الازدحام",
  "preferences.price": "حساسية السعر",
  "preferences.transfer": "تقليل التحويلات",
  "preferences.walking": "المشي",
  "preferences.options.section": "خيارات التوجيه",
  "preferences.options.maxWalkingDistance": "الحد الأقصى للمشي (م)",
  "preferences.options.maxTotalWalkingDistance":
    "الحد الأقصى لإجمالي المشي (م)",
  "preferences.options.maxWalkingNeighbors": "أقصى جيران للمشي",
  "preferences.options.maxBusTransfers": "أقصى تحويلات باص",
  "preferences.options.walkingSpeed": "سرعة المشي (م/ث)",
  "preferences.hint.min50": "الحد الأدنى 50",
  "preferences.hint.rangeWalkTotal": "المدى 0 .. 10000",
  "preferences.hint.rangeNeighbors": "المدى 1 .. 100",
  "preferences.hint.rangeTransfers": "المدى 0 .. 10",
  "preferences.hint.rangeSpeed": "المدى 0.4 .. 3.5",
  "preferences.save": "حفظ التفضيلات",
  "preferences.saveError": "تعذر حفظ التفضيلات.",

  "history.title": "سجل الرحلات",
  "history.subtitle": "المستخدم #{id} - آخر {limit} رحلات",
  "history.refresh": "تحديث",
  "history.loading": "جاري تحميل السجل...",
  "history.loadError":
    "تعذر تحميل سجل الرحلات. اسحب لإعادة المحاولة أو اضغط تحديث.",
  "history.empty": "لا توجد رحلات محفوظة بعد.",
  "history.delete": "حذف",
  "history.deleteTitle": "حذف الرحلة",
  "history.deleteBody": "هل تريد حذف هذا العنصر من سجل الرحلات؟",
  "history.deleteSuccess": "تم حذف عنصر السجل.",
  "history.deleteError": "تعذر حذف عنصر السجل.",
  "history.unknownOrigin": "بداية غير معروفة",
  "history.unknownDest": "وجهة غير معروفة",
  "history.unknownTime": "وقت غير معروف",
  "history.metric.transfers": "التحويلات",
  "history.metric.distance": "المسافة",
  "history.metric.duration": "المدة",
  "history.metric.routes": "الخطوط",
  "history.useAgain": "استخدم مرة أخرى",
  "history.completedTrip": "رحلة مكتملة",
  "history.cachedRouteLoaded": "تم تحميل المسار المحفوظ",

  "planner.title": "مخطط الرحلة",
  "planner.pref.loading": "جاري تحميل التفضيلات...",
  "planner.pref.saved": "يتم استخدام التفضيلات المحفوظة",
  "planner.pref.defaults": "يتم استخدام القيم الافتراضية",
  "planner.start": "البداية",
  "planner.destination": "الوجهة",
  "planner.tapStart": "المس الخريطة: تحديد البداية",
  "planner.tapDestination": "المس الخريطة: تحديد الوجهة",
  "planner.locked": "المسار مقفل. اضغط مسح لاختيار وجهة جديدة.",
  "planner.request": "طلب مسار",
  "planner.clear": "مسح",
  "planner.actions": "إجراءات المسار",
  "planner.preferences": "التفضيلات",
  "planner.filter.balanced": "الأفضل",
  "planner.filter.fastest": "الأسرع",
  "planner.filter.fewestTransfers": "تحويلات أقل",
  "planner.filter.lessWalking": "مشي أقل",
  "planner.filter.cheapest": "الأرخص",
  "planner.filter.lessCrowded": "ازدحام أقل",
  "planner.textPlaceholder": "مثال: من باب توما إلى الحمرا",
  "planner.useText": "استخدام النص",
  "planner.nlp.title": "اكتب رحلتك",
  "planner.nlp.needOrigin": "منين بدك تنطلق؟",
  "planner.nlp.needDestination": "وين بدك تروح؟",
  "planner.nlp.needClarification": "أي مكان قصدك؟",

  "prefModal.title": "تفضيلات المسار",
  "prefModal.subtitle": "هذه الخيارات تغير طريقة البحث عن المسار",
  "prefModal.loading": "جاري تحميل التفضيلات...",
  "prefModal.walkingTolerance": "كم مشي مناسب لك؟",
  "prefModal.walkingDescription": "يحدد أطول مشي إلى المواقف وإجمالي المشي في المسار.",
  "prefModal.walking.low": "مشي قصير",
  "prefModal.walking.medium": "مشي عادي",
  "prefModal.walking.high": "مشي أطول",
  "prefModal.transferLimit": "كم تغيير باص؟",
  "prefModal.transferDescription": "يحدد عدد مرات تغيير الباص في المسار.",
  "prefModal.transfer.none": "مباشر فقط",
  "prefModal.transfer.one": "تغيير واحد",
  "prefModal.transfer.two": "تغييران",
  "prefModal.transfer.flexible": "خيارات أكثر",
  "prefModal.walkingPace": "سرعة مشيك",
  "prefModal.paceDescription": "تستخدم لحساب وقت المشي.",
  "prefModal.pace.slow": "هادئ",
  "prefModal.pace.normal": "متوسط",
  "prefModal.pace.fast": "سريع",
  "prefModal.searchBreadth": "كم خيار مسار؟",
  "prefModal.breadthDescription": "البحث الأوسع قد يجد مسارات أفضل لكنه قد يستغرق وقتا أطول.",
  "prefModal.breadth.compact": "بحث أسرع",
  "prefModal.breadth.balanced": "متوازن",
  "prefModal.breadth.wide": "خيارات أكثر",
  "prefModal.cancel": "إلغاء",
  "prefModal.save": "حفظ",

  "search.placeholder": "ابحث عن مكان على الخريطة",
  "map.startFallback": "موقعك",
  "map.destinationFallback": "اختر الوجهة",
  "map.destinationPin": "الوجهة",
  "map.pinnedStart": "نقطة البداية",
  "map.pinnedDestination": "الوجهة المحددة",
  "map.mapPoint": "محدد على الخريطة",

  "route.eta": "الوقت المتوقع",
  "route.min": "د",
  "route.transfer": "تحويل",
  "route.transfers": "التحويلات",
  "route.walk": "المشي",
  "route.share.action": "مشاركة",
  "route.share.title": "مسار قابل للمشاركة",
  "route.share.start": "البداية",
  "route.share.destination": "الوجهة",
  "route.share.googleMapsLabel": "الفتح في خرائط Google",
  "route.share.appLinkLabel": "الفتح في تطبيق JR",
  "route.share.universalLinkLabel": "فتح رابط المسار",
  "route.share.failedTitle": "فشلت المشاركة",
  "route.share.failedBody": "تعذر مشاركة هذا المسار الآن.",
  "route.trip.ready": "جاهز للانطلاق",
  "route.trip.inProgress": "المسار قيد الاستخدام",
  "route.trip.startHint": "ابدأ عندما تستخدم هذا المسار فعلا.",
  "route.trip.finishHint": "أنه الرحلة عند الوصول لحفظها.",
  "route.trip.start": "ابدأ",
  "route.trip.finish": "إنهاء",
  "route.trip.saving": "جاري الحفظ",
  "route.trip.started": "بدأ المسار",
  "route.trip.saved": "تم حفظ المسار",
  "route.trip.saveFailedTitle": "تعذر حفظ الرحلة",
  "route.trip.saveFailed": "تعذر حفظ هذه الرحلة الآن.",
  "routePoint": "نقطة مسار",

  "steps.walk": "مشي",
  "steps.takeBus": "اركب باص",
  "steps.routeFallback": "خط",
  "steps.via": "عبر",

  "feedback.title": "تقييم الرحلة",
  "feedback.hide": "إخفاء",
  "feedback.give": "أضف تقييم",
  "feedback.route": "الخط",
  "feedback.summary": "ملخص تقييم الخط (30 يوم)",
  "feedback.loadingSummary": "جاري تحميل الملخص...",
  "feedback.reports": "عدد التقارير",
  "feedback.avgPrice": "متوسط السعر",
  "feedback.avgCrowding": "متوسط الازدحام",
  "feedback.avgSpeed": "متوسط السرعة",
  "feedback.avgSlowness": "متوسط البطء",
  "feedback.crowdingTendency": "ميل الازدحام",
  "feedback.speedSuggestion": "اقتراح السرعة",
  "feedback.lastReport": "آخر تقرير",
  "feedback.noSummary": "لا يوجد ملخص بعد.",
  "feedback.reportedPrice": "السعر المبلّغ",
  "feedback.crowdingLevel": "مستوى الازدحام",
  "feedback.speedLevel": "مستوى السرعة",
  "feedback.slownessLevel": "مستوى البطء",
  "feedback.comment": "تعليق (اختياري)",
  "feedback.commentPlaceholder": "شارك تجربتك",
  "feedback.skip": "تخطي",
  "feedback.submit": "إرسال التقييم",
  "feedback.thanks": "شكرًا",
  "feedback.submitted": "تم إرسال التقييم بنجاح.",
  "feedback.missingRouteTitle": "الخط غير محدد",
  "feedback.missingRouteBody": "اختر خط باص لإرسال التقييم.",
  "feedback.invalidPriceTitle": "سعر غير صالح",
  "feedback.invalidPriceBody": "يجب أن يكون السعر 0 أو أكبر.",

  "home.error.missingPointsTitle": "نقاط ناقصة",
  "home.error.missingPointsBody": "يجب تحديد نقطة البداية والوجهة.",
  "home.error.routeFailedTitle": "فشل طلب المسار",
  "home.error.searchNoPlaceTitle": "لم يتم العثور على مكان",
  "home.error.searchNoPlaceBody": "جرّب اسم مكان أكثر دقة.",
  "home.error.searchFailedTitle": "فشل البحث",
  "home.error.searchFailedBody": "تعذر البحث عن الأماكن الآن.",
  "home.error.locationPermission": "لم يتم منح إذن الموقع.",
  "home.filterUpdateFailedTitle": "فشل تحديث الفلتر",
  "home.chooseDestinationFirstTitle": "اختر الوجهة أولًا",
  "home.chooseDestinationFirstBody": "اختر وجهة على الخريطة أو عبر البحث قبل تحديد نقطة البداية.",
  "home.crosshair.title": "اختر نقطة البداية",
  "home.crosshair.subtitle": "حرّك الخريطة وضع الدبوس في المكان المناسب",
  "home.crosshair.set": "تحديد",
  "home.origin.header": "اختر نقطة الانطلاق",
  "home.origin.chooseFromMap": "اختر من الخريطة",
  "home.origin.useCurrent": "استخدم موقعي الحالي",
  "home.origin.favorites": "المفضلة",
  "home.origin.saveCurrentFavorite": "احفظ موقعي الحالي كمفضلة",
  "home.startHereTitle": "ابدأ من هنا",
  "home.startHereBody": "اختر وجهة، ثم نقطة بداية، وبعدها اطلب المسار.",
  "home.results.publicTransport": "النقل العام",
  "home.results.tapToExpand": "اضغط على مسار لعرض التفاصيل",
  "home.results.routeDetails": "تفاصيل المسار",
  "home.results.live": "مسار مباشر",
  "home.results.liveFallback": "مسار احتياطي مباشر",
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>("en");
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      try {
        const stored = await SecureStore.getItemAsync(STORAGE_KEY);
        if (stored === "ar" || stored === "en") {
          setLanguageState(stored);
        }
      } finally {
        setIsLoading(false);
      }
    };

    void load();
  }, []);

  const setLanguage = async (next: AppLanguage) => {
    setLanguageState(next);
    await SecureStore.setItemAsync(STORAGE_KEY, next);
  };

  const dictionary = language === "ar" ? ar : en;

  const value = useMemo<LanguageContextType>(
    () => ({
      language,
      isRTL: language === "ar",
      isLoading,
      setLanguage,
      t: (key: string) => dictionary[key] ?? en[key] ?? key,
    }),
    [dictionary, isLoading, language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
