export const locationSchema = {
  type: "object",
  required: ["lat", "lng"],
  properties: {
    lat: { type: "number", minimum: -90, maximum: 90 },
    lng: { type: "number", minimum: -180, maximum: 180 },
    label: { type: "string" },
  },
};

export const navigationRouteSchema = {
  tags: ["Navigation"],
  summary: "Compute best route",
  operationId: "computeNavigationRoute",
  body: {
    type: "object",
    required: ["from", "to"],
    properties: {
      from: locationSchema,
      to: locationSchema,
      preferences: {
        type: "object",
        additionalProperties: false,
        properties: {
          speed: { type: "number", minimum: 0 },
          crowding: { type: "number", minimum: 0 },
          price: { type: "number", minimum: 0 },
          transfer: { type: "number", minimum: 0 },
          walking: { type: "number", minimum: 0 },
        },
      },
      options: {
        type: "object",
        additionalProperties: false,
        properties: {
          maxWalkingDistanceM: { type: "number", minimum: 50 },
          maxTotalWalkingDistanceM: { type: "number", minimum: 0, maximum: 10000 },
          maxWalkingNeighbors: { type: "integer", minimum: 1, maximum: 100 },
          maxBusTransfers: { type: "integer", minimum: 0, maximum: 10 },
          walkingSpeedMps: { type: "number", minimum: 0.4, maximum: 3.5 },
          walkLinearCoeff: { type: "number", minimum: 0, maximum: 5 },
          walkExpCoeff: { type: "number", minimum: 0, maximum: 2 },
          walkExpScaleM: { type: "number", minimum: 100, maximum: 5000 },
          transferExpCoeff: { type: "number", minimum: 0, maximum: 5 },
          transferExpRate: { type: "number", minimum: 0.1, maximum: 3 },
        },
      },
    },
  },
  response: {
    200: {
      type: "object",
      required: [
        "message",
        "executedInWorker",
        "graphLoadedAt",
        "graphVersion",
        "from",
        "to",
        "totalCost",
        "components",
        "transferCount",
        "walkingDistanceM",
        "etaSeconds",
        "segments",
        "bestEffort",
        "usedConfig",
      ],
      properties: {
        message: { type: "string" },
        executedInWorker: { type: "boolean" },
        graphLoadedAt: { type: ["string", "null"] },
        graphVersion: { type: ["string", "null"] },
        from: locationSchema,
        to: locationSchema,
        totalCost: { type: "number" },
        components: {
          type: "object",
          required: ["speed", "crowding", "price", "transfer", "walking"],
          properties: {
            speed: { type: "number" },
            crowding: { type: "number" },
            price: { type: "number" },
            transfer: { type: "number" },
            walking: { type: "number" },
          },
        },
        transferCount: { type: "integer" },
        walkingDistanceM: { type: "number" },
        etaSeconds: { type: "number" },
        bestEffort: { type: "boolean" },
        segments: {
          type: "array",
          items: {
            type: "object",
            required: ["mode", "routeId", "routeName", "from", "to", "distanceM", "timeSeconds", "cost"],
            properties: {
              mode: { type: "string", enum: ["walk", "bus"] },
              routeId: { type: ["integer", "null"] },
              routeName: { type: ["string", "null"] },
              from: locationSchema,
              to: locationSchema,
              distanceM: { type: "number" },
              timeSeconds: { type: "number" },
              cost: { type: "number" },
            },
          },
        },
        usedConfig: {
          type: "object",
          required: [
            "weights",
            "maxWalkingDistanceM",
            "maxTotalWalkingDistanceM",
            "maxWalkingNeighbors",
            "maxBusTransfers",
            "walkingSpeedMps",
            "walkLinearCoeff",
            "walkExpCoeff",
            "walkExpScaleM",
            "transferExpCoeff",
            "transferExpRate",
          ],
          properties: {
            weights: {
              type: "object",
              required: ["speed", "crowding", "price", "transfer", "walking"],
              properties: {
                speed: { type: "number" },
                crowding: { type: "number" },
                price: { type: "number" },
                transfer: { type: "number" },
                walking: { type: "number" },
              },
            },
            maxWalkingDistanceM: { type: "number" },
            maxTotalWalkingDistanceM: { type: "number" },
            maxWalkingNeighbors: { type: "integer" },
            maxBusTransfers: { type: "integer" },
            walkingSpeedMps: { type: "number" },
            walkLinearCoeff: { type: "number" },
            walkExpCoeff: { type: "number" },
            walkExpScaleM: { type: "number" },
            transferExpCoeff: { type: "number" },
            transferExpRate: { type: "number" },
          },
        },
      },
    },
    401: {
      type: "object",
      required: ["error"],
      properties: {
        error: { type: "string" },
      },
    },
    500: {
      type: "object",
      required: ["error"],
      properties: {
        error: { type: "string" },
        details: { type: "string" },
      },
    },
    504: {
      type: "object",
      required: ["error"],
      properties: {
        error: { type: "string" },
        details: { type: "string" },
      },
    },
  },
};